name: Build

on: [push]

jobs:
  build:
    name: Re:VIEW Workflow
    runs-on: ubuntu-latest
    container: docker://vvakame/review:3.1
    steps:
      - uses: actions/checkout@v2
      - name: Create PDF
        run: |
          cd src
          review pdfmaker config-print.yml
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: src/*.pdf
          retention-days: 3